service: s3Loop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 3008
  timeout: 900

functions:
  s3Loop:
    handler: index.handler
    name: s3Loop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::058264250962:role/DeployLambdaRole
    #reservedConcurrency: 1
    events:
      - schedule: rate(5 minutes)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 's3Loop_${opt:stage, self:provider.stage}'
